POST http://localhost:5001/patients
Content-Type: application/json

{
    "patientName": "Rajendran",
    "dateOfBirth": "2003/06/30",
    "address": "Valangaiman",
    "contactNumber": "1234597890",
    "gender": "M",
    "bloodGroup": "O+",
    "weight": "77",
    "height": "172"
}

###
GET http://localhost:5001/patients/p00010

###
PUT http://localhost:5001/patients/p00012
Content-Type: application/json

{
    "patientName":"Will Wheaton"
}
###
GET http://localhost:5001/doctors/

###
GET http://localhost:5001/doctors/available

###
GET http://localhost:5001/doctors/d005

###
POST http://localhost:5001/doctors
Content-Type: application/json

{
    "doctorName": "karthi",
    "doctorSpecialization": "ortho",
    "doctorDateOfBirth": "2001/12/14",
    "contactNumber": "3456789212",
    "address": "Nagarkovil",
    "doctorGender": "M"
}

###
PUT http://localhost:5001/doctors/d003
Content-Type: application/json

{
    "doctorName": "pragadeesh"
}

###
DELETE http://localhost:5001/doctors/d001

###

POST http://localhost:5001/login/doctor
Content-Type: application/json

{
    "doctorId": "d001",
    "doctorDateOfBirth": "23/6/1912"
}

###
POST http://localhost:5001/login/patient
Content-Type: application/json

{
    "patientId": "p00001",
    "patientDateOfBirth": "15/6/1985"
}

###

POST http://localhost:5001/visits
Content-Type: application/json

{
    "patientId": "p00010",
    "doctorId": "d006",
    "dateOfVisit": "2025/05/25"
}

###

POST http://localhost:5001/login/doctor
Content-Type: application/json

{
    "doctorId": "d001",
    "doctorDateOfBirth": "15/06/1985"
}
###
GET http://localhost:5001/visits/doctor/d001/allPending

###
GET http://localhost:5001/visits/doctor/d004/today

###
GET http://localhost:5001/visits/

###
POST http://localhost:5001/visits/
Content-Type: application/json

{
    "patientId": "p00012",
    "doctorId": "d006",
    "dateOfVisit": "2025/06/27"
}
###
GET http://localhost:5001/reports

###
GET http://localhost:5001/reports?patientId=p00001

###
GET http://localhost:5001/visits/patient/pending?patientId=p00001

###

